# Generated by Django 4.2.30 on 2026-06-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_orders', models.IntegerField()),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cash_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('card_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Daily Revenues',
                'ordering': ['-date'],
            },
        ),
    ]
