# Generated by Django 4.2.30 on 2026-06-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='occupied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
